#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Separates data from all specified files -- created by run_experiments.rb 
# and then processed by separate_by_alg (!) -- by input size.

for infile in "$@"; do
  ns=`cat "${infile}" | tail -n +2 | cut -f2 | uniq`;
  alg=`cat "${infile}" | tail -n +2 | head -1 | cut -f1`;
  name="${infile%.tab}";
  
  for n in ${ns}; do
    head -1 "${infile}" > "${name}_${n}.tab";
    grep ${alg}[[:space:]]${n}[[:space:]] "${infile}" >> "${name}_${n}.tab";
  done
done
