#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Separates data from all files created by run_experiments.rb that
# can be found in the current directory, by algorithm.

for infile in {avg,}times-*.tab; do
  algs=`cat "${infile}" | tail -n +2 | cut -f1 | uniq`;
  expname="${infile%.tab}";
  
  for alg in ${algs}; do
    head -1 "${infile}" > "${alg}_${expname}.tab";
    grep ${alg}[[:space:]] "${infile}" >> "${alg}_${expname}.tab";
  done
done
